# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Dienstnummer')),
                ('dienstbeginn', models.DateTimeField(verbose_name='Dienstbeginn')),
                ('dienstende', models.DateTimeField(verbose_name='Dienstende')),
            ],
        ),
        migrations.CreateModel(
            name='Dienstart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Dienstart')),
            ],
        ),
        migrations.CreateModel(
            name='Dienstgebiet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=50, verbose_name='Nachname')),
                ('vorname', models.CharField(max_length=50, verbose_name='Vorname')),
                ('handy', models.CharField(max_length=20, verbose_name='Handynummer')),
                ('adresse_strasse', models.CharField(max_length=100, verbose_name='Stra\xdfe & Hnr.')),
                ('adresse_plz', models.CharField(max_length=6, verbose_name='PLZ')),
                ('adresse_ort', models.CharField(max_length=100, verbose_name='Stadt')),
                ('geb_datum', models.DateField(verbose_name='Geburtsdatum')),
                ('bw_eintritt', models.DateField(verbose_name='Bergwacht-Eintritt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dienst',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dienstplan.Dienstart'),
        ),
        migrations.AddField(
            model_name='dienst',
            name='dienstgebiet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dienstplan.Dienstgebiet'),
        ),
    ]
