# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dienstplan', '0002_auto_20170726_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutzer',
            name='adresse_ort',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='nutzer',
            name='adresse_plz',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='nutzer',
            name='adresse_strasse',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stra\xdfe & Hnr.'),
        ),
        migrations.AlterField(
            model_name='nutzer',
            name='bw_eintritt',
            field=models.DateField(blank=True, null=True, verbose_name='Bergwacht-Eintritt'),
        ),
        migrations.AlterField(
            model_name='nutzer',
            name='geb_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='nutzer',
            name='handy',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Handynummer'),
        ),
        migrations.AlterField(
            model_name='nutzer',
            name='nachname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='nutzer',
            name='vorname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vorname'),
        ),
    ]
