# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-27 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dienstplan', '0004_auto_20170727_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='dienst',
            name='bemerkung',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Bemerkungen'),
        ),
    ]
